kind: Pod
apiVersion: v1
metadata:
  name: mongoserver
spec:
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
       claimName: mongo-pv-claim
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
          hostPort: 27017
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo-pv-storage