kind: Pod
apiVersion: v1
metadata:
  name: mongodb
spec:
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
       claimName: mongo-pv-claim
  containers:
    - name: task-pv-container
      image: mongo
      ports:
        - containerPort: 27107
          name: "mongodb"
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo-pv-storage